### ISSUE TITLE
ERROR  HttpError: Invalid request.  No subschema in "anyOf" matched.

### ISSUE THREAD

**Issue by nareshbulusu** [octoherd/script-sync-branch-protections#7]
@gr2m I am getting the below error when I try to use the latest version.

```
nareshkumarbulusus-MacBook-Pro:~ nareshkumar.bulusu$ npx @octoherd/script-sync-branch-protections --template "sede-x/shell-innersource-iac-terraform" -T "${GITHUB_TOKEN}" -R "sede-x/iiac-sync-policies-test1"
npx: installed 120 in 5.863s

Running @octoherd/cli v3.3.1 (@octoherd/octokit v2.3.1, Node.js: v14.16.1, darwin x64)

 INFO  Loading repositories ...
.
 INFO  Running on sede-x/iiac-sync-policies-test1 ...
 INFO  branch protection settings loaded from sede-x/shell-innersource-iac-terraform {"required_status_checks":{"strict":true,"contexts":[]},"enforce_admins":true,"required_pull_request_reviews":{"dismiss_stale_reviews":false,"require_code_owner_reviews":true,"dismissal_restrictions":{"users":[],"teams":[{"name":"innersource-iac-maintainers","id":4654565,"node_id":"MDQ6VGVhbTQ2 … }
✔ Do you want to allow the following request:

  Update branch protection
  route:                         PUT /repos/{owner}/{repo}/branches/{branch}/protection
  owner:                         sede-x
  repo:                          iiac-sync-policies-test1
  branch:                        main
  required_status_checks:        [object Object]
  enforce_admins:                true
  required_pull_request_reviews: [object Object]
  restrictions:                  null
  required_linear_history:       true
  allow_force_pushes:            false
  allow_deletions:               false
  msg:                           branch protection settings loaded from sede-x/shell-innersource-iac-terraform

  https://docs.github.com/rest/reference/repos#update-branch-protection
 · yes
 ERROR  HttpError: Invalid request.

No subschema in "anyOf" matched.
For 'items', {"name"=>"innersource-iac-maintainers", "id"=>4654565, "node_id"=>"MDQ6VGVhbTQ2NTQ1NjU=", "slug"=>"innersource-iac-maintainers", "description"=>"", "privacy"=>"closed", "permission"=>"pull"} is not a string.
Not all subschemas of "allOf" matched.
For 'anyOf/1', {"dismiss_stale_reviews"=>false, "require_code_owner_reviews"=>true, "dismissal_restrictions"=>{"users"=>[], "teams"=>[{"name"=>"innersource-iac-maintainers", "id"=>4654565, "node_id"=>"MDQ6VGVhbTQ2NTQ1NjU=", "slug"=>"innersource-iac-maintainers", "description"=>"", "privacy"=>"closed", "permission"=>"pull"}]}} is not a null.
    at /Users/nareshkumar.bulusu/.npm/_npx/3109/lib/node_modules/@octoherd/script-sync-branch-protections/node_modules/@octokit/request/dist-node/index.js:68:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Job.doExecute (/Users/nareshkumar.bulusu/.npm/_npx/3109/lib/node_modules/@octoherd/script-sync-branch-protections/node_modules/bottleneck/light.js:405:18) {"name":"HttpError","status":422,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-S … }

--------------------------------------------------------------------------------

```

**Comment by gr2m** [comment]
Thanks Naresh I'll have a look

**Comment by gr2m** [comment]
Can you check if #8 fixed your problem? A new version of the script should be released momentarily

**Comment by nareshbulusu** [comment]
@gr2m I'll give it a try now

**Comment by nareshbulusu** [comment]
@gr2m It works now, Thanks a lot for your help. Much appreciated 💯
